---
- name: Ricing Arch System
  hosts: local
  become: true
  vars:
    ansible_user_id: "ansible"
    main_user_id: "arch"
  gather_facts: false
  roles:
    - base
    - yay
    - ssh
    - shell
    - firewall
#    - loginmanager
#    - devtools
#    - hyprland
#    - waybar
#    - dotfiles
#    - backup
