---
- name: Install firewalld
  ansible.builtin.pacman:
    name:
      - firewalld
    state: present
    update_cache: yes

- name: Enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: Gather firewalld facts
  ansible.posix.firewalld_facts:

- name: Print all firewalld facts
  debug:
    var: ansible_facts.firewalld.zones


- name: Set default zone to home
  ansible.builtin.command: firewall-cmd --set-default-zone=home

- name: Set default policy for outgoing to ACCEPT
  ansible.builtin.command: firewall-cmd --zone=home --set-target=ACCEPT


- name: Allow SSH
  ansible.posix.firewalld:
    service: ssh
    zone: home
    state: enabled
    immediate: true
    permanent: true

- name: Allow icmp-echo-request
  ansible.posix.firewalld:
    icmp_block_inversion: false
    zone: home
    icmp_block: echo-request
    state: disabled
    immediate: true
    permanent: true
