---
- name: Install firewalld
  ansible.builtin.pacman:
    name:
      - firewalld
    state: present
    update_cache: yes

- name: Enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: Gather firewalld facts
  ansible.posix.firewalld_info:
  register: firewalld_info

#- name: Print all firewalld facts
#  debug:
#    var: firewalld_info

- name: Check current default firewall zone
  ansible.builtin.command: firewall-cmd --get-default-zone
  register: current_zone
  changed_when: current_zone.stdout != "home"


- name: Set default zone to home
  ansible.builtin.command: firewall-cmd --set-default-zone=home
  when: current_zone.stdout != "home"

- name: Allow SSH
  ansible.posix.firewalld:
    service: ssh
    zone: home
    state: enabled
    immediate: true
    permanent: true

- name: Remove ICMP echo-request block
  ansible.posix.firewalld:
    zone: home
    state: disabled
    icmp_block: echo-request
    permanent: yes
    immediate: yes


- name: Allow ICMP ping
  ansible.posix.firewalld:
    zone: home
    icmp_block_inversion: false
    state: enabled
    permanent: yes
    immediate: yes
