# Ansible-managed SSH server config fragment
# Global options (must come BEFORE any Match blocks)

PasswordAuthentication no
PermitRootLogin prohibit-password
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Specific rule for root user
Match User root
    AuthenticationMethods publickey
    PermitRootLogin yes