---
- name: Install SDDM
  ansible.builtin.pacman:
    name: sddm
    state: present

- name: Copy Config File
  ansible.builtin.template:
    src: 10-hyprland.conf.j2
    dest: /etc/sddm.conf.d/10-hyprland.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable SDDM
  ansible.builtin.systemd:
    name: sddm.service
    enabled: true
    state: started