---
- name: Install SSH server
  ansible.builtin.pacman:
    name: openssh
    state: present
    update_cache: yes

- name: Enable SSH service
  ansible.builtin.systemd:
    name: sshd
    enabled: true
    state: started

- name: Configure SSH server
  ansible.builtin.copy:
    src: files/99-ansible.conf
    dest: /etc/ssh/sshd_config.d/99-ansible.conf
    owner: root
    group: root
    mode: '0644'
    notify:
        - Restart SSH service

- name: Ensure root's .ssh directory exists
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Add public key for root login
  ansible.builtin.copy:
    src: files/authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: '0600'
