---
- name: Install zsh
  ansible.builtin.pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: present
    update_cache: yes

- name: Set Zsh for main user
  ansible.builtin.user:
    name: "{{ main_user_id }}"
    shell: /usr/bin/zsh

- name: Copy zsh config to main user
  ansible.builtin.template:
    src: zprofile
    dest: "/home/{{ main_user_id }}/.zprofile"
    owner: "{{ main_user_id }}"
    group: "{{ main_user_id }}"
    mode: '0644'
  when: main_user_id is defined